title: "Jeremy Bastoky's Recipes"
author: Jeremy Bastoky
# github_username:  jnbastoky

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/jnbastoky/Recipes"

include:
  - ".attachments"

theme: minima
header_pages: ['']
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
#   - jekyll-remote-theme
